apiVersion: apps/v1
kind: Deployment 
metadata:
  name: drawzy-frontend
  namespace: drawzy-staging
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: drawzy-frontend
  template:
    metadata:
      labels:
        app: drawzy-frontend
    spec:
      restartPolicy: Always

      tolerations:
        - key: "env"
          operator: "Equal" #the key and value must exactly match with taint #Exits
          value: "staging"
          effect: "NoSchedule" #New pods will not be scheduled unless they have a matching toleration #PreferNoSchedule, NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # pod will only be scheduled on matching nodes. If no matching node exists, the pod stays in Pending state.
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In 
                    values:
                      - staging 

      
      securityContext: #Applies to all containers unless overridden
        runAsUser: 10001 #Container processes run as UID 10001
        runAsGroup: 30001 #Primary GID for processes
        fsGroup: 20001  #Mounted volumes owned by this group
        runAsNonRoot: true #Pod will fail if image runs as root
        seccompProfile:
          type: RuntimeDefault

      # initContainers:
      #   - name: wait-for-postgres
      #     image: busybox:1.35
      #     command: ['sh', '-c', 'until nc -z postgresdb-svc  5432; do echo "Waiting for Postgres..."; sleep 2; done']
      containers:
        - name: drawzy-frontend
          image: ajayt8374/drawzy:1.1.1

          securityContext:  #Overrides or adds container-specific restrictions.
            allowPrivilegeEscalation: false #Prevents setuid, sudo, etc.
            readOnlyRootFilesystem: true  #Protects root FS from writes
            capabilities:
              drop:
                - ALL
          
          # imagePullPolicy: Always #  to ensure you're always working with the latest image changes 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: drawzy-secrets
                  key: JWT_SECRET
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: drawzy-secrets
                  key: NEXTAUTH_SECRET
            - name: DATABASE_URL
              # value: postgresql://Drawzy:drawzy0987654321@postgresdb-svc:5432/Drawzy_Staging
              valueFrom:
                secretKeyRef:
                  name: drawzy-secrets
                  key:  DATABASE_URL
          # requests and limits
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          # probes
          livenessProbe:  #liveness probe fails, the pod is restarted
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5 # Start checking 5 seconds after the container starts
            periodSeconds: 10     # Probe runs every 10 seconds
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: next-cache
              mountPath: /.next
      volumes:
        - name: tmp
          emptyDir: {}
        - name: next-cache
          emptyDir: {}