name: Build and Push Container Images

on:
  push:
    branches:
      - main
    paths:
      - apps/**
    tags:
      - "**@[0-9]*.[0-9]*.[0-9]*"
  workflow_dispatch:
    inputs:
      service:
        description: "Apps to build"
        type: choice
        required: true
        options:
          - apps/drawzy
          - apps/ws
      version:
        description: "Version/tag to use (optional; defaults generating with git describe)"
        required: false
        type: string

jobs:
  security:
    runs-on: ubutnu-24.04
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - name: Run Synk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.set-output.outputs.services }}
      environment: ${{ steps.set-output.outputs.environment }}
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main' }}

      - name: Paths Changes Filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

      - name: Set Output
        id: set-output
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              echo 'services=["${{ inputs.service }}"]' >> "$GITHUB_OUTPUT"
              echo 'environment=development' >> "$GITHUB_OUTPUT"

          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
              tag="${GITHUB_REF_NAME}"
              svc="${tag%%@*}"
              echo "services=[\"$svc\"]" >> "$GITHUB_OUTPUT"
              echo 'environment=production' >> "$GITHUB_OUTPUT"

          else
              echo 'services=${{ steps.filter.outputs.changes }}' >> "$GITHUB_OUTPUT"
              echo 'environment=staging' >> "$GITHUB_OUTPUT"
          fi

  build-push-container-images:
    runs-on: ubuntu-24.04
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    needs: filter
    strategy:
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
            # Setting fetch-depth: 0 ensure tags are fetched (so git describe works properly)
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@05340d1c670183e7caabdb33ae9f1c80fae3b0c2 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a # v3.11.1

      - name: Compute image tag
        id: image-tag
        working-directory: ${{ matrix.service }}
        env:
          ENVIRONMENT: ${{ needs.filter.outputs.environment }}
          INPUT_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.version || '' }}
          SERVICE: ${{ matrix.service }}
        run: |
          # Rule 1: Manual version (workflow_dispatch)
          if [[ -n "$INPUT_VERSION" ]]; then
            version="$INPUT_VERSION"
            image_tag="${SERVICE}:${version}"

          # Rule 2: Production (tag build)
          elif [[ "$ENVIRONMENT" == "production" ]]; then
            version="${GITHUB_REF_NAME}"
            image_tag="${SERVICE}:${version}"

          # Rule 3: Other environments â†’ auto version using git describe
          else
            version=$(git describe --always --dirty --tags)
            image_tag="${SERVICE}:${version}"
          fi

          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "image_tag=${image_tag}" >> "$GITHUB_OUTPUT"

      - name: Select Dockerfile
        id: dockerfile
        run: |
          if [[ "${{ matrix.service }}" == "apps/drawzy" ]]; then
            echo "dockerfile=docker/Dockerfile.frontend" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.service }}" == "apps/ws" ]]; then
            echo "dockerfile=docker/Dockerfile.websocket" >> "$GITHUB_OUTPUT"
          else
            echo "Unknown service: ${{ matrix.service }}"
            exit 1
          fi

      - name: Extract service name
        id: service
        run: echo "name=$(basename ${{ matrix.service }})" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build & Push Docker Images
        uses: docker/build-push-action@ccc2b40e9ea6518f9252a22a990f8e868370f62e
        with:
          context: .
          file: ${{ steps.dockerfile.outputs.dockerfile }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ steps.service.outputs.name }}:${{ steps.image-tag.outputs.version }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ steps.service.outputs.name }}:latest
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max